[2022-09-06T00:00:03.293+0000] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: another_dag.inaccurate scheduled__2022-09-05T00:00:00+00:00 [queued]>
[2022-09-06T00:00:03.301+0000] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: another_dag.inaccurate scheduled__2022-09-05T00:00:00+00:00 [queued]>
[2022-09-06T00:00:03.302+0000] {taskinstance.py:1368} INFO - 
--------------------------------------------------------------------------------
[2022-09-06T00:00:03.303+0000] {taskinstance.py:1369} INFO - Starting attempt 1 of 1
[2022-09-06T00:00:03.303+0000] {taskinstance.py:1370} INFO - 
--------------------------------------------------------------------------------
[2022-09-06T00:00:03.311+0000] {taskinstance.py:1389} INFO - Executing <Task(BashOperator): inaccurate> on 2022-09-05 00:00:00+00:00
[2022-09-06T00:00:03.315+0000] {standard_task_runner.py:52} INFO - Started process 68717 to run task
[2022-09-06T00:00:03.318+0000] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'another_dag', 'inaccurate', 'scheduled__2022-09-05T00:00:00+00:00', '--job-id', '734', '--raw', '--subdir', 'DAGS_FOLDER/another_dag.py', '--cfg-path', '/tmp/tmpj8s39vow', '--error-file', '/tmp/tmpouam8p68']
[2022-09-06T00:00:03.319+0000] {standard_task_runner.py:80} INFO - Job 734: Subtask inaccurate
[2022-09-06T00:00:03.366+0000] {task_command.py:371} INFO - Running <TaskInstance: another_dag.inaccurate scheduled__2022-09-05T00:00:00+00:00 [running]> on host 071ffc5e88f8
[2022-09-06T00:00:03.409+0000] {taskinstance.py:1583} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=another_dag
AIRFLOW_CTX_TASK_ID=inaccurate
AIRFLOW_CTX_EXECUTION_DATE=2022-09-05T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-09-05T00:00:00+00:00
[2022-09-06T00:00:03.411+0000] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-09-06T00:00:03.412+0000] {subprocess.py:74} INFO - Running command: ['/bin/bash', '-c', "echo 'inaccurate'"]
[2022-09-06T00:00:03.424+0000] {subprocess.py:85} INFO - Output:
[2022-09-06T00:00:03.426+0000] {subprocess.py:92} INFO - inaccurate
[2022-09-06T00:00:03.427+0000] {subprocess.py:96} INFO - Command exited with return code 0
[2022-09-06T00:00:03.448+0000] {taskinstance.py:1412} INFO - Marking task as SUCCESS. dag_id=another_dag, task_id=inaccurate, execution_date=20220905T000000, start_date=20220906T000003, end_date=20220906T000003
[2022-09-06T00:00:03.492+0000] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-09-06T00:00:03.514+0000] {local_task_job.py:279} INFO - 0 downstream tasks scheduled from follow-on schedule check
