[2022-08-24T19:40:53.268+0000] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: another_dag.inaccurate scheduled__2022-08-23T00:00:00+00:00 [queued]>
[2022-08-24T19:40:53.277+0000] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: another_dag.inaccurate scheduled__2022-08-23T00:00:00+00:00 [queued]>
[2022-08-24T19:40:53.280+0000] {taskinstance.py:1368} INFO - 
--------------------------------------------------------------------------------
[2022-08-24T19:40:53.281+0000] {taskinstance.py:1369} INFO - Starting attempt 1 of 1
[2022-08-24T19:40:53.283+0000] {taskinstance.py:1370} INFO - 
--------------------------------------------------------------------------------
[2022-08-24T19:40:53.293+0000] {taskinstance.py:1389} INFO - Executing <Task(BashOperator): inaccurate> on 2022-08-23 00:00:00+00:00
[2022-08-24T19:40:53.298+0000] {standard_task_runner.py:52} INFO - Started process 23972 to run task
[2022-08-24T19:40:53.301+0000] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'another_dag', 'inaccurate', 'scheduled__2022-08-23T00:00:00+00:00', '--job-id', '19', '--raw', '--subdir', 'DAGS_FOLDER/another_dag.py', '--cfg-path', '/tmp/tmp7y4sh1ut', '--error-file', '/tmp/tmp3ysw0699']
[2022-08-24T19:40:53.302+0000] {standard_task_runner.py:80} INFO - Job 19: Subtask inaccurate
[2022-08-24T19:40:53.345+0000] {task_command.py:371} INFO - Running <TaskInstance: another_dag.inaccurate scheduled__2022-08-23T00:00:00+00:00 [running]> on host 9ab687ae92a7
[2022-08-24T19:40:53.389+0000] {taskinstance.py:1583} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=another_dag
AIRFLOW_CTX_TASK_ID=inaccurate
AIRFLOW_CTX_EXECUTION_DATE=2022-08-23T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-08-23T00:00:00+00:00
[2022-08-24T19:40:53.391+0000] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-08-24T19:40:53.392+0000] {subprocess.py:74} INFO - Running command: ['/bin/bash', '-c', "echo 'inaccurate'"]
[2022-08-24T19:40:53.403+0000] {subprocess.py:85} INFO - Output:
[2022-08-24T19:40:53.405+0000] {subprocess.py:92} INFO - inaccurate
[2022-08-24T19:40:53.406+0000] {subprocess.py:96} INFO - Command exited with return code 0
[2022-08-24T19:40:53.426+0000] {taskinstance.py:1412} INFO - Marking task as SUCCESS. dag_id=another_dag, task_id=inaccurate, execution_date=20220823T000000, start_date=20220824T194053, end_date=20220824T194053
[2022-08-24T19:40:53.473+0000] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-08-24T19:40:53.499+0000] {local_task_job.py:279} INFO - 0 downstream tasks scheduled from follow-on schedule check
