[2022-09-02T01:59:12.002+0000] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: another_dag.inaccurate manual__2022-09-02T01:59:09.353104+00:00 [queued]>
[2022-09-02T01:59:12.009+0000] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: another_dag.inaccurate manual__2022-09-02T01:59:09.353104+00:00 [queued]>
[2022-09-02T01:59:12.010+0000] {taskinstance.py:1368} INFO - 
--------------------------------------------------------------------------------
[2022-09-02T01:59:12.011+0000] {taskinstance.py:1369} INFO - Starting attempt 1 of 1
[2022-09-02T01:59:12.012+0000] {taskinstance.py:1370} INFO - 
--------------------------------------------------------------------------------
[2022-09-02T01:59:12.020+0000] {taskinstance.py:1389} INFO - Executing <Task(BashOperator): inaccurate> on 2022-09-02 01:59:09.353104+00:00
[2022-09-02T01:59:12.024+0000] {standard_task_runner.py:52} INFO - Started process 41991 to run task
[2022-09-02T01:59:12.026+0000] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'another_dag', 'inaccurate', 'manual__2022-09-02T01:59:09.353104+00:00', '--job-id', '652', '--raw', '--subdir', 'DAGS_FOLDER/another_dag.py', '--cfg-path', '/tmp/tmp01luba2j', '--error-file', '/tmp/tmp2n6nhzy4']
[2022-09-02T01:59:12.027+0000] {standard_task_runner.py:80} INFO - Job 652: Subtask inaccurate
[2022-09-02T01:59:12.100+0000] {task_command.py:371} INFO - Running <TaskInstance: another_dag.inaccurate manual__2022-09-02T01:59:09.353104+00:00 [running]> on host 0f8c666ea2b1
[2022-09-02T01:59:12.144+0000] {taskinstance.py:1583} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=another_dag
AIRFLOW_CTX_TASK_ID=inaccurate
AIRFLOW_CTX_EXECUTION_DATE=2022-09-02T01:59:09.353104+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-09-02T01:59:09.353104+00:00
[2022-09-02T01:59:12.146+0000] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-09-02T01:59:12.148+0000] {subprocess.py:74} INFO - Running command: ['/bin/bash', '-c', "echo 'inaccurate'"]
[2022-09-02T01:59:12.157+0000] {subprocess.py:85} INFO - Output:
[2022-09-02T01:59:12.159+0000] {subprocess.py:92} INFO - inaccurate
[2022-09-02T01:59:12.160+0000] {subprocess.py:96} INFO - Command exited with return code 0
[2022-09-02T01:59:12.179+0000] {taskinstance.py:1412} INFO - Marking task as SUCCESS. dag_id=another_dag, task_id=inaccurate, execution_date=20220902T015909, start_date=20220902T015912, end_date=20220902T015912
[2022-09-02T01:59:12.204+0000] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-09-02T01:59:12.225+0000] {local_task_job.py:279} INFO - 0 downstream tasks scheduled from follow-on schedule check
